apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhtap-python-app-1 
  janus-idp.io/tekton: rhtap-python-app-1
  backstage.io/kubernetes-id: rhtap-python-app-1
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhtap-python-app-1
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml