apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rhtap-python-app-1-gitops
  description: This is GitOps manifest for rhtap-python-app-1   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=rhtap-python-app-1
    backstage.io/kubernetes-id: rhtap-python-app-1 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: mvaldron-rhdh/rhtap-python-app-1-gitops
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: mvaldron-rhdh.rhtap-python-app-1-gitops
spec:
  type: gitops
  owner: user:default/michael-valdron 
  lifecycle: experimental
  dependsOn:
    - component:rhtap-python-app-1
